Controllers/ChangePasswordController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using tufol.Models;
using tufol.Interfaces;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Options;

namespace tufol.Controllers
{
    public class ChangePasswordController : Controller
    {
        private IMenu _menu;
        private IUser _user;
        private readonly IStringLocalizer<HomeController> _localizer;
        private readonly IEnumerable<MenuModel> _list_menu;
        private readonly Helpers.AppSettings _appSettings;
        public ChangePasswordController(IMenu menu, IUser user, IHttpContextAccessor httpContextAccessor, IStringLocalizer<HomeController> localizer, IOptions<Helpers.AppSettings> appSettings)
        {
            _menu = menu;
            _user = user;
            _appSettings = appSettings.Value;

            _localizer = localizer;
            _list_menu = _menu.GetMenu(httpContextAccessor.HttpContext.Session.GetString("role_id"));
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Menu = _list_menu;
            ViewData["name"] = HttpContext.Session.GetString("name");
            ViewData["idRole"] = HttpContext.Session.GetString("idRole");
            return View();
        }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [PreventDuplicateRequest]
    public IActionResult Index(string currentPassword, string NewPassword, string verifyPassword)
    {
      ViewBag.Menu = _list_menu;
      ViewBag.BaseUrl = _appSettings.BaseUrl;
      ViewBag.Menu = _list_menu;
      string user_id = HttpContext.Session.GetString("user_id");
      ViewData["name"] = HttpContext.Session.GetString("name");
      ViewData["idRole"] = HttpContext.Session.GetString("idRole");
      
      var encPass = new Helpers.GlobalFunction().GetMD5(currentPassword);
      var inEncPass = new Helpers.GlobalFunction().GetMD5(NewPassword);
      var dataPassword = _user.GetPassword(encPass,user_id);

      // Console.WriteLine(dataPassword);

      if (encPass != dataPassword)
      {
        // Console.WriteLine("Password not found" + dataPassword);
        ViewBag.error = _localizer.GetString("InvalidPassword");
        return View("~/Views/ChangePassword/Index.cshtml");
      }
      if (NewPassword != verifyPassword)
      {
        ViewBag.error = _localizer.GetString("PasswordMustBeSame");
        return View("~/Views/ChangePassword/Index.cshtml");

      }
      int UpdatedPassword = _user.UpdateByPassword(inEncPass,user_id);

      // Console.WriteLine(UpdatedPassword);
      
      if(UpdatedPassword > 0 ){
        ViewBag.reset_success = "Password has been successfully updated";
        return View("~/Views/ChangePassword/Index.cshtml");
      }else {
        ViewBag.error = "Something went wrong, unable to update the password";
        return View("~/Views/ChangePassword/Index.cshtml");
      }

      //  ViewBag.registration_success = "Password berhasil di ubah";


    }
  }
}

Views/ChangePassword/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;
@{
    ViewData["Title"] = Localizer["Title"];
}
<!--begin::Content-->
<!--begin::Card-->
<div class="card card-custom">
    <!--begin::Header-->
    <div class="card-header py-3">
        <div class="card-title align-items-start flex-column">
            <h3 class="card-label font-weight-bolder text-dark">@ViewData["Title"]</h3>
            <span class="text-muted font-weight-bold font-size-sm mt-1">@Localizer["SubTitle"]</span>
        </div>
    </div>
    <!--end::Header-->
    <!--begin::Form-->
    <form class="form" method="POST" asp-controller="ChangePassword" asp-action="Index">
        <div class="card-body">
            <div class="form-group row">
                <label class="col-xl-3 col-lg-3 col-form-label text-alert">@Localizer["CurrentPassword"]</label>
                <div class="col-lg-9 col-xl-9">
                    <input type="password" class="form-control form-control-lg form-control-solid mb-2" value=""
                        placeholder='@Localizer["CurrentPassword"]' name="currentPassword" required="required" />
                    @* <a href="#" class="text-sm font-weight-bold">Forgot password ?</a> *@
                </div>
            </div>
            <div class="form-group row">
                <label class="col-xl-3 col-lg-3 col-form-label text-alert">@Localizer["NewPassword"]</label>
                <div class="col-lg-9 col-xl-9">
                    <input type="password" class="form-control form-control-lg form-control-solid" value=""
                        placeholder='@Localizer["NewPassword"]' name="NewPassword" required="required" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-xl-3 col-lg-3 col-form-label text-alert">@Localizer["VerifyPassword"]</label>
                <div class="col-lg-9 col-xl-9">
                    <input type="password" class="form-control form-control-lg form-control-solid" value=""
                        placeholder='@Localizer["VerifyPassword"]' name="verifyPassword" required="required" />
                </div>
            </div>
            <div class="card-toolbar">
                <button type="submit" name="action" class="btn btn-success mr-2">@Localizer["Save"]</button>
                <button type="reset" class="btn btn-secondary">@Localizer["Back"]</button>
            </div>
        </div>
    </form>
    <!--end::Form-->
</div>
<!--end::Content-->

@section Scripts {
<script type="text/javascript">
    let error = "@ViewBag.error"
    if (error) {
        swal.fire({
            text: error,
            icon: "error",
            buttonsStyling: false,
            confirmButtonText: "Ok!",
            customClass: {
                confirmButton: "btn font-weight-bold btn-light-primary"
            }
        }).then(function () {
            KTUtil.scrollTop();
        });
    }

    let reset_success = "@ViewBag.reset_success"
    if (reset_success) {
        swal.fire({
            text: reset_success,
            icon: "success",
            buttonsStyling: false,
            confirmButtonText: "Ok!",
            customClass: {
                confirmButton: "btn font-weight-bold btn-light-primary"
            }
        }).then(function () {
            KTUtil.scrollTop();
        });
    }
</script>
}